name: Divisifieur Workflow
on: [push]
jobs:
  build:
    runs-on : ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Gradlew build
        run: ./gradlew build

      - name : Jar
        run: java -jar build/libs/*.jar 3 1

      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Arti Divisifieur
          path: build/libs/*.jar
